import{a as m,S as f,i}from"./assets/vendor-BPs2jpei.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const g="https://pixabay.com/api/",y="38315380-10eeb0cf3b6e9a9ad49e9c507";async function v(e,a=1){try{return(await m.get(g,{params:{key:y,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}})).data}catch(o){throw console.error("Error fetching data from Pixabay API",o),o}}const u=document.querySelector(".gallery-list");function L(e){const a=e.map(s=>`<li class="image-wrapper">
    <a href="${s.largeImageURL}">
    <img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${s.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${s.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${s.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${s.downloads}</p></div>
    </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",a)}function b(){u.innerHTML=""}const w=document.querySelector(".form"),x=document.querySelector(".form-input"),h=document.querySelector(".loader"),n=document.querySelector(".load-btn");let c=1,d="";const P=new f(".gallery-list a",{captions:!0,captionsData:"alt",captionDelay:250});w.addEventListener("submit",S);n.addEventListener("click",q);async function S(e){if(e.preventDefault(),b(),c=1,d=x.value.trim(),!d){i.warning({position:"bottomRight",message:"Please enter a search term"});return}await p()}async function q(){c+=1,await p(),R()}async function p(){h.classList.remove("hidden"),n.classList.add("hidden");try{const e=await v(d,c);e.totalHits===0?i.warning({position:"bottomRight",message:"Sorry, there are no images matching your search query. Please try again!"}):(L(e.hits),P.refresh(),e.hits.length<15||c*15>=e.totalHits?(n.classList.add("hidden"),i.info({position:"bottomRight",message:"We're sorry, but you've reached the end of search results."})):n.classList.remove("hidden"))}catch(e){i.error({position:"bottomRight",message:"Failed to fetch images."}),console.error(e)}finally{h.classList.add("hidden")}}function R(){const{height:e}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
